In [11]:
import pandas as pd

In [12]:
# 1 creating dataframe
df = pd.DataFrame([11,22,33], columns =['col_Name'] )
print (df)

   col_Name
0        11
1        22
2        33

In [13]:
print (type(df))

<class 'pandas.DataFrame'>

In [16]:
data = {
    'Name' : [ 'Madhav', 'Vishkha', 'lavanya', 'Rishi'],
    'Age'  : [ 16,17,18,19],
    'Salary':[90000 , 70000, 50000, 30000]
}

In [17]:
df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0   Madhav   16   90000
1  Vishkha   17   70000
2  lavanya   18   50000
3    Rishi   19   30000

In [18]:
print(type(df))

<class 'pandas.DataFrame'>

In [ ]:
#2. Basic Data Frame Understing

In [19]:
df.head(2)  # it gives the Top row

      Name  Age  Salary
0   Madhav   16   90000
1  Vishkha   17   70000

In [20]:
df.tail(2)  # it gives last Row

      Name  Age  Salary
2  lavanya   18   50000
3    Rishi   19   30000

In [21]:
df.shape

(4, 3)

In [22]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [23]:
df.rename(columns = { 'Salary' : 'Monthly_Salary'}, inplace = True)

In [24]:
print(df)

      Name  Age  Monthly_Salary
0   Madhav   16           90000
1  Vishkha   17           70000
2  lavanya   18           50000
3    Rishi   19           30000

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [26]:
df.describe()

             Age  Monthly_Salary
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

In [ ]:
# 3. Save and load Data From csv

In [27]:
df.to_csv('emp_detais.csv', index=False)  # Its is export Data

In [28]:
load_df = pd.read_csv('emp_detais.csv')   # Its imports data
load_df

      Name  Age  Monthly_Salary
0   Madhav   16           90000
1  Vishkha   17           70000
2  lavanya   18           50000
3    Rishi   19           30000

In [ ]:
#4 . Row & Column - Selection

In [29]:
# Select column
df['Name']   # Tis is singl colunm

df[['Name' , 'Monthly_Salary']]

      Name  Monthly_Salary
0   Madhav           90000
1  Vishkha           70000
2  lavanya           50000
3    Rishi           30000

In [30]:
# Select Row
# This is loc - index name basesd
# df.loc[df.Name == 'Madhav']
df.loc[(df.Name == 'Madhav') & (df.Monthly_Salary >=50000)]

     Name  Age  Monthly_Salary
0  Madhav   16           90000

In [31]:
# iloc  - index value based

# df.iloc[0]

df.iloc[0:2] # [Start:stop:step]

      Name  Age  Monthly_Salary
0   Madhav   16           90000
1  Vishkha   17           70000

In [ ]:
#5 . Filter dataframe

In [32]:
df

      Name  Age  Monthly_Salary
0   Madhav   16           90000
1  Vishkha   17           70000
2  lavanya   18           50000
3    Rishi   19           30000

In [36]:
df['Age'] >18

0    False
1    False
2    False
3     True
Name: Age, dtype: bool

In [37]:
df[df['Age'] >18]

    Name  Age  Monthly_Salary
3  Rishi   19           30000

In [45]:
df_age_filter = df[df['Age'] >=18]

In [46]:
df_age_filter

      Name  Age  Monthly_Salary
2  lavanya   18           50000
3    Rishi   19           30000

In [47]:
df[(df['Age'] >=18) & (df['Monthly_Salary'] >=50000)]

      Name  Age  Monthly_Salary
2  lavanya   18           50000

In [48]:
df.where(df['Age']>=18)

      Name   Age  Monthly_Salary
0      NaN   NaN             NaN
1      NaN   NaN             NaN
2  lavanya  18.0         50000.0
3    Rishi  19.0         30000.0

In [49]:
df.where(df['Age']>=18, other = 'Not Eligible')

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2       lavanya            18          50000
3         Rishi            19          30000

In [50]:
#6. Row and column operations (Add, Update, Delete)

In [51]:
df

      Name  Age  Monthly_Salary
0   Madhav   16           90000
1  Vishkha   17           70000
2  lavanya   18           50000
3    Rishi   19           30000

In [52]:
#add new Column

df['Team'] = ['CEO', 'HR', 'CTO', 'Da']

In [81]:
df['Bonus'] = df['Monthly_Salary'] * 0.2

In [87]:
df

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   16           90000  CEO  18000.0
1  Vishkha   17           70000   HR  14000.0
2  lavanya   18           50000  CTO  10000.0
3    Rishi   19           30000   Da   6000.0
4      ABC   21           21000   IT   4200.0
5    Rahul   21           85000   HR  17000.0
6    Niraj   22           55000   IT  11000.0

In [67]:
#add new row 

df.loc[len(df)] = [ 'Niraj',22,55000,'IT',55000 * 0.2]

In [78]:
df

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   16           90000  CEO  18000.0
1  Vishkha   17           70000   HR  14000.0
2  lavanya   18           50000  CTO  10000.0
3    Rishi   19           30000   Da   6000.0
4      ABC   21           21000   IT   4200.0
5    Rahul   21           85000   HR  17000.0
6    Niraj   22           55000   IT  11000.0

In [72]:
#update values - using index name and loc method

df.loc[5, 'Name' ] = 'Rahul'
df

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   16           90000  CEO  18000.0
1  Vishkha   17           70000   HR  14000.0
2  lavanya   18           50000  CTO  10000.0
3    Rishi   19           30000   Da   6000.0
4      ABC   21           21000   IT   4200.0
5    Rahul   21           21000   IT   4200.0
6    Niraj   22           55000   IT  11000.0

In [73]:
df.loc[5, 'Team' ] = 'HR'
df

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   16           90000  CEO  18000.0
1  Vishkha   17           70000   HR  14000.0
2  lavanya   18           50000  CTO  10000.0
3    Rishi   19           30000   Da   6000.0
4      ABC   21           21000   IT   4200.0
5    Rahul   21           21000   HR   4200.0
6    Niraj   22           55000   IT  11000.0

In [79]:
df.loc[5, 'Monthly_Salary' ] = 85000
df

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   16           90000  CEO  18000.0
1  Vishkha   17           70000   HR  14000.0
2  lavanya   18           50000  CTO  10000.0
3    Rishi   19           30000   Da   6000.0
4      ABC   21           21000   IT   4200.0
5    Rahul   21           85000   HR  17000.0
6    Niraj   22           55000   IT  11000.0

In [141]:
df.loc[0,'Monthly_Salary'] = 95000
df

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   16           95000  CEO  19000.0
1  Vishkha   17           70000   HR  14000.0
2  lavanya   18           50000  CTO  10000.0
3    Rishi   19           30000   Da   6000.0
4      ABC   21           21000   IT   4200.0
5    Rahul   21           85000   HR  17000.0
6    Niraj   22           55000   IT  11000.0

In [152]:
# update value - using column values

In [166]:
df.loc[df.Name == 'Madhav' ,'Monthly_Salary'] = 90000
df

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   16           90000  CEO  19000.0
1  Vishkha   17           70000   HR  14000.0
2  lavanya   18           50000  CTO  10000.0
3    Rishi   19           30000   Da   6000.0
4      ABC   21           21000   IT   4200.0
5    Rahul   21           85000   HR  17000.0
6    Niraj   22           55000   IT  11000.0

In [167]:
df['Bonus'] = df['Monthly_Salary'] * 0.2

In [168]:
df

      Name  Age  Monthly_Salary Team    Bonus
0   Madhav   16           90000  CEO  18000.0
1  Vishkha   17           70000   HR  14000.0
2  lavanya   18           50000  CTO  10000.0
3    Rishi   19           30000   Da   6000.0
4      ABC   21           21000   IT   4200.0
5    Rahul   21           85000   HR  17000.0
6    Niraj   22           55000   IT  11000.0

In [ ]:
# delete Vlaues - row & column

In [175]:
df = df.drop(df[df.Name == 'ABC'].index)

In [183]:
df

      Name  Age  Monthly_Salary Team
0   Madhav   16           90000  CEO
1  Vishkha   17           70000   HR
2  lavanya   18           50000  CTO
3    Rishi   19           30000   Da
5    Rahul   21           85000   HR
6    Niraj   22           55000   IT

In [193]:
# deleted column
df.drop('Team',axis = 1, inplace =True)
df

      Name  Age  Monthly_Salary
0   Madhav   16           90000
1  Vishkha   17           70000
2  lavanya   18           50000
3    Rishi   19           30000
5    Rahul   21           85000
6    Niraj   22           55000

In [195]:
df = df.drop(df[df['Name'].isin(['Niraj', 'Rahul'])].index)

In [196]:
df

      Name  Age  Monthly_Salary
0   Madhav   16           90000
1  Vishkha   17           70000
2  lavanya   18           50000
3    Rishi   19           30000

In [ ]:
#7. Workig With dateValues

In [199]:
df['Doj'] = ['2024-01-01', '2024-01-15', '2024-03-28', '2024-03-03']
df

      Name  Age  Monthly_Salary         Doj
0   Madhav   16           90000  2024-01-01
1  Vishkha   17           70000  2024-01-15
2  lavanya   18           50000  2024-03-28
3    Rishi   19           30000  2024-03-03

In [201]:
df['Doj'].dtype

In [203]:
df['Doj'] = pd.to_datetime(df['Doj'])

In [204]:
df['Doj'].dtype

dtype('<M8[us]')

In [ ]:
df1 =